### ISSUE TITLE
Episode gets partially downloaded when connection interrupted

### ISSUE THREAD

**Issue by NekoMimiOfficial** [rebelonion/Dantotsu-Download-Addon#1]
Assuming you directly pipe the m3u8 stream into the transformer this will yield an incomplete but viewable episode when the connection is disconnected or interrupted 

You may first download the m3u8 file/data with a DECENT download manager, (ps: whatever dantotsu used to do before creating this addon was perfect for when the internet connection gets interrupted) then convert it into an mp4 file and clean up afterwards 

~luv u rebel
Your's truly, Neko <3 😂

**Comment by rebelonion** [comment]
The way it was done before was internally in exoplayer (basically universally hated by the users). 
Also I'd like to keep the issue consolidated, so I'll use the open thread in discord. 
Thx tho
